### ISSUE TITLE
ULRA - Workflow Modeling up to Ingest

### ISSUE THREAD

**Issue by jeremyf** [ndlib/sipity#949]
There exists a workflow for the ULRA submissions; However it is not complete.

## States

- [x] New
- [x] Pending advisor completion
- [x] Pending student completion
- [x] Under review
- [x] Review completed

## State Changing Actions

- [x] Student portion complete; Available to student in New state
  - [x] Send email to advisor
- [x] Faculty portion complete; Available to faculty in New state
  - [x] Send email to student
- [x] Submit for review
  - [x] Available to student when "Pending student completion"
  - [x] Available to advisor when "Pending advisor completion"
  - [x] Send email to student

## Forms

- [x] SubmitStudentPortionForm (state changing)
- [x] SubmitFacultyPortionForm (state changing)

## Todo Actions

See #948

**Comment by jeremyf** [comment]
Closed via #951
